# Generated by Django 5.2.8 on 2025-11-25 02:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_habit_start_date_habitlog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
