# Generated by Django 5.2.8 on 2025-11-25 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_habitlog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
