# Generated by Django 5.2.8 on 2025-12-06 06:00

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_alter_habitlog_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='due_date',
            field=models.DateField(default=1988),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='notes',
            field=ckeditor.fields.RichTextField(default='image/upload/v1764080147/fiuunrdp0alvekzr8rzn.webp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1764080147/fiuunrdp0alvekzr8rzn.webp', max_length=255),
            preserve_default=False,
        ),
    ]
